const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('lowlevel', {
  runTool: (name, input) => ipcRenderer.invoke('tool:run', name, input),
  bootstrap: () => ipcRenderer.invoke('bootstrap'),
  remoteCall: (baseUrl, tool, input) => ipcRenderer.invoke('remote:call', baseUrl, tool, input),
  getConnections: () => ipcRenderer.invoke('connections:get'),
  setConnections: (connections) => ipcRenderer.invoke('connections:set', connections),
  getAgents: () => ipcRenderer.invoke('agents:get'),
  setAgents: (agents) => ipcRenderer.invoke('agents:set', agents),
  getTools: () => ipcRenderer.invoke('tools:list'),
  startApi: (host, port) => ipcRenderer.invoke('api:start', host, port),
  stopApi: () => ipcRenderer.invoke('api:stop'),
  apiStatus: () => ipcRenderer.invoke('api:status'),
  removeStartup: () => ipcRenderer.invoke('startup:remove'),
  startupStatus: () => ipcRenderer.invoke('startup:status'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (settings) => ipcRenderer.invoke('settings:set', settings),
  getHistory: () => ipcRenderer.invoke('history:get'),
  getNotifications: () => ipcRenderer.invoke('notifications:get'),
  addNotification: (notification) => ipcRenderer.invoke('notifications:add', notification),
  clearNotifications: () => ipcRenderer.invoke('notifications:clear'),
  getTabs: () => ipcRenderer.invoke('tabs:get'),
  setTabs: (tabs) => ipcRenderer.invoke('tabs:set', tabs),
  exportText: (text) => ipcRenderer.invoke('export:text', text),
  openExternal: (url) => ipcRenderer.invoke('open:external', url),
  browsePath: (kind) => ipcRenderer.invoke('browse:path', kind),
  saveFile: (suggestedName, contentBase64) => ipcRenderer.invoke('file:save', suggestedName, contentBase64),
  getChangelog: () => ipcRenderer.invoke('changelog:get'),
  getReleaseCodename: () => ipcRenderer.invoke('release:codename'),
  getMemory: () => ipcRenderer.invoke('memory:list'),
  createMemoryCheckpoint: (label) => ipcRenderer.invoke('memory:create', label),
  restoreMemoryCheckpoint: (id) => ipcRenderer.invoke('memory:restore', id)
});
