const $ = (id) => document.getElementById(id);
const show = (message) => { $('snackbar').textContent = message; $('snackbar').classList.add('show'); setTimeout(() => $('snackbar').classList.remove('show'), 3500); };
const json = (id) => { try { return JSON.parse($(id).value || '{}'); } catch (e) { throw new Error(`JSON parameters are invalid: ${e.message}`); } };
let desktops = [];
let connections = [];

document.querySelectorAll('.tab').forEach((tab) => tab.addEventListener('click', () => {
  document.querySelectorAll('.tab').forEach((item) => item.classList.toggle('active', item === tab));
  document.querySelectorAll('.page').forEach((page) => page.classList.toggle('active', page.id === tab.dataset.tab));
  if (tab.dataset.tab === 'history') loadHistory();
}));

async function run(name, input) { $('statusText').textContent = `Running ${name}…`; const target = $('targetConnection')?.value || 'local'; const connection = connections.find((item) => item.id === target); const result = connection ? await window.lowlevel.remoteCall(connection.url, name, input) : await window.lowlevel.runTool(name, input); $('statusText').textContent = result.ok ? 'Ready' : 'Needs attention'; $('toolOutput').textContent = JSON.stringify(result, null, 2); return result; }
async function refreshDesktops() { const result = await run('list_headless_desktops', {}); desktops = result.desktops || []; $('desktopList').innerHTML = desktops.length ? desktops.map((d) => `<div class="history-item"><strong>${d.name}</strong><br><span class="support">${d.window_count} window(s) · ${d.full}</span></div>`).join('') : '<p class="empty">No desktops owned by this server process.</p>'; $('desktopSelect').innerHTML = desktops.length ? desktops.map((d) => `<option value="${d.name}">${d.name}</option>`).join('') : '<option>No desktops</option>'; }
$('createDesktops').addEventListener('click', async () => { try { const prefix = `${$('project').value}-${$('agent').value}`.replace(/[^A-Za-z0-9_-]/g, '-'); await run('create_headless_desktops', { count: Number($('desktopCount').value), prefix }); await refreshDesktops(); show('Headless desktops ready without touching the visible desktop.'); } catch (e) { show(e.message); } });
$('refreshDesktops').addEventListener('click', refreshDesktops);
$('launchApp').addEventListener('click', async () => { try { await run('launch_on_headless_desktop', { name: $('desktopSelect').value, command: $('launchCommand').value }); await refreshDesktops(); show('Application launched on the selected hidden desktop.'); } catch (e) { show(e.message); } });
$('startApi').addEventListener('click', async () => { const result = await window.lowlevel.startApi($('apiHost').value, Number($('apiPort').value)); $('apiResult').textContent = result.ok ? `Running at http://${result.host}:${result.port}/mcp · health ${result.health}` : result.error; show(result.ok ? 'LAN API is hosted headless.' : 'API did not start.'); });
$('stopApi').addEventListener('click', async () => { await window.lowlevel.stopApi(); $('apiResult').textContent = 'Stopped'; show('LAN API stopped.'); });
$('installStartup').addEventListener('click', async () => { const result = await window.lowlevel.installStartup($('apiHost').value, Number($('apiPort').value), false); $('apiResult').textContent = result.ok ? 'API scheduled at user logon.' : (result.stderr || result.stdout || 'Startup installation failed.'); show(result.ok ? 'Run on logon enabled.' : 'Startup installation needs attention.'); });
$('removeStartup').addEventListener('click', async () => { const result = await window.lowlevel.removeStartup(); $('apiResult').textContent = result.ok ? 'Logon task removed.' : (result.stderr || result.stdout || 'Could not remove startup task.'); show(result.ok ? 'Run on logon removed.' : 'Startup removal needs attention.'); });
$('connectRemote').addEventListener('click', async () => { const name = $('remoteName').value.trim(); const url = $('remoteUrl').value.trim().replace(/\/$/, ''); if (!name || !url) { show('Name and API URL are required.'); return; } const result = await window.lowlevel.remoteCall(url, 'list_headless_desktops', {}); if (!result.ok) { $('remoteStatus').textContent = result.error || 'Remote connection failed.'; show('Could not connect to the remote API.'); return; } const existing = connections.find((item) => item.url === url); const item = existing || { id: `${Date.now()}`, name, url }; item.name = name; connections = [...connections.filter((candidate) => candidate.id !== item.id), item]; await window.lowlevel.setConnections(connections); await loadConnections(); $('remoteSelect').value = item.id; $('targetConnection').value = item.id; $('remoteStatus').textContent = `Connected: ${url}/api/execute · headless desktop preferred`; show('Remote computer saved for agents to pick up.'); });

async function loadConnections() { connections = await window.lowlevel.getConnections(); const options = ['<option value="local">Local cheap tools</option>', ...connections.map((item) => `<option value="${item.id}">${item.name} · ${item.url}</option>`)].join(''); $('remoteSelect').innerHTML = options; $('targetConnection').innerHTML = options; }
$('remoteSelect').addEventListener('change', () => { $('targetConnection').value = $('remoteSelect').value; });
$('runTool').addEventListener('click', async () => { try { await run($('toolName').value, json('toolInput')); } catch (e) { $('toolOutput').textContent = e.message; show(e.message); } });
$('installDeps').addEventListener('click', async () => { $('statusText').textContent = 'Installing quietly…'; const result = await window.lowlevel.bootstrap(); $('statusText').textContent = result.ok ? 'Ready' : 'Needs attention'; show(result.ok ? 'Dependencies are ready.' : `Dependency setup stopped at ${result.stage}.`); });

async function loadHistory() { const query = $('historySearch').value.toLowerCase(); const pattern = $('regexPattern').value; const flags = $('regexFlags').value; let matcher; try { matcher = pattern ? new RegExp(pattern, flags) : { test: (x) => x.toLowerCase().includes(query) }; $('regexResult').textContent = pattern ? 'Valid regex.' : 'Plain text is active.'; } catch { $('regexResult').textContent = 'Invalid regex; no results changed.'; return; } const entries = await window.lowlevel.getHistory(); const filtered = entries.filter((e) => matcher.test(`${e.tool} ${JSON.stringify(e.input)} ${JSON.stringify(e.result)}`)); $('historyList').innerHTML = filtered.length ? filtered.map((e) => `<article class="history-item"><code>${e.tool}</code> <span class="support">${e.at}</span><pre>${JSON.stringify(e.result, null, 2)}</pre></article>`).join('') : '<p class="empty">No matching command history.</p>'; }
$('historySearch').addEventListener('input', loadHistory); $('regexPattern').addEventListener('input', loadHistory); $('regexFlags').addEventListener('input', loadHistory); $('regexToggle').addEventListener('click', () => $('regexPanel').classList.toggle('open'));
$('exportHistory').addEventListener('click', async () => { const entries = await window.lowlevel.getHistory(); const file = await window.lowlevel.exportText(`# Low-Level Computer-Use history\n\n${entries.map((e) => `## ${e.tool} — ${e.at}\n\n\`\`\`json\n${JSON.stringify(e.result, null, 2)}\n\`\`\``).join('\n\n')}`); show(`Exported ${file}`); });

async function loadSettings() { const s = await window.lowlevel.getSettings(); $('language').value = s.language; $('englishFunny').value = s.englishFunny; $('cantoneseFunny').value = s.cantoneseFunny; $('theme').value = s.theme; $('density').value = s.density; $('accent').value = s.accent; $('fontScale').value = s.fontScale; applySettings(s); }
function applySettings(s) { document.documentElement.style.setProperty('--accent', s.accent); document.documentElement.style.fontSize = `${16 * Number(s.fontScale || 1)}px`; document.documentElement.dataset.density = s.density; if (s.theme === 'light') { document.documentElement.style.setProperty('--bg', '#f8f8ff'); document.documentElement.style.setProperty('--surface', '#eef0f8'); document.documentElement.style.setProperty('--surface2', '#e0e3ed'); document.documentElement.style.setProperty('--text', '#1a1b20'); document.documentElement.style.setProperty('--muted', '#45464f'); document.documentElement.style.colorScheme = 'light'; } }
$('saveSettings').addEventListener('click', async () => { const s = { language: $('language').value, englishFunny: Number($('englishFunny').value), cantoneseFunny: Number($('cantoneseFunny').value), theme: $('theme').value, density: $('density').value, accent: $('accent').value, fontScale: Number($('fontScale').value) }; await window.lowlevel.setSettings(s); applySettings(s); show('Settings saved for this user.'); });
$('openDocs').addEventListener('click', () => window.lowlevel.openExternal('https://codingmachineedge.github.io/lowlevel-computer-use-mcp/'));
loadSettings(); loadConnections(); refreshDesktops();
